#!/usr/bin/env python3
"""roadmap_validator — Control Plane roadmap state validation + markdown projection.

This is intentionally small and deterministic. It supports the Control Plane-first
operating model:

* ``roadmap-state.json`` is machine-owned Control Plane state.
* ``docs/milestone-backlog.md`` is a generated human-readable projection.
* In ``single_milestone`` mode, ``charter.yaml`` is the active execution source and
  a stale/absent ``campaign-plan.json`` does not block delivery.
* In ``campaign`` mode, ``campaign-plan.json`` is the executable multi-milestone
  queue and must match the roadmap state.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, field
from typing import Any, Optional

try:
    from jsonschema import Draft202012Validator
except ImportError:  # pragma: no cover
    sys.stderr.write("roadmap_validator: jsonschema is required\n")
    raise


ROADMAP_STATE_REL = ".orchestrator/control/roadmap-state.json"
ROADMAP_MUTATIONS_REL = ".orchestrator/control/roadmap-mutations.jsonl"


@dataclass
class Issue:
    level: str
    rule: str
    message: str
    path: str = ""

    def render(self) -> str:
        tag = "ERROR" if self.level == "error" else "WARN "
        loc = f" @ {self.path}" if self.path else ""
        return f"[{tag}] {self.rule}: {self.message}{loc}"


@dataclass
class Report:
    errors: list[Issue] = field(default_factory=list)
    warnings: list[Issue] = field(default_factory=list)

    def error(self, rule: str, message: str, path: str = "") -> None:
        self.errors.append(Issue("error", rule, message, path))

    def warn(self, rule: str, message: str, path: str = "") -> None:
        self.warnings.append(Issue("warning", rule, message, path))

    @property
    def ok(self) -> bool:
        return not self.errors

    def merge(self, other: "Report") -> None:
        self.errors.extend(other.errors)
        self.warnings.extend(other.warnings)

    def render(self) -> str:
        lines = [i.render() for i in self.errors] + [i.render() for i in self.warnings]
        if not lines:
            lines.append("roadmap_validator: OK.")
        lines.append(f"{len(self.errors)} error(s), {len(self.warnings)} warning(s).")
        return "\n".join(lines)


def _find_schema(schema_name: str) -> str:
    cur = os.path.abspath(os.path.dirname(__file__))
    while True:
        cand = os.path.join(cur, "schemas", schema_name)
        if os.path.isfile(cand):
            return cand
        parent = os.path.dirname(cur)
        if parent == cur:
            raise FileNotFoundError(f"schema not found: {schema_name}")
        cur = parent


def _load_schema(schema_name: str) -> dict:
    with open(_find_schema(schema_name), "r", encoding="utf-8") as fh:
        return json.load(fh)


def _read_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def _validate_obj(obj: Any, schema_name: str, *, path: str) -> Report:
    report = Report()
    validator = Draft202012Validator(_load_schema(schema_name))
    errors = sorted(validator.iter_errors(obj), key=lambda e: list(e.absolute_path))
    for e in errors:
        loc = ".".join(str(p) for p in e.absolute_path) or "<root>"
        report.error("roadmap_schema_invalid", f"{loc}: {e.message}", path)
    return report


def _status_label(status: str) -> str:
    return {
        "planned": "planned",
        "needs_research_gate1": "needs Research gate-1",
        "signed_gate1": "gate-1 signed",
        "active": "ACTIVE",
        "closed": "CLOSED",
        "deferred": "deferred",
    }.get(status, status)


def _deps(deps: list[str]) -> str:
    return ", ".join(deps) if deps else "-"


def render_backlog(state: dict) -> str:
    """Render the generated human-readable roadmap projection."""
    mode = state.get("delivery_mode")
    refs = state.get("source_refs") or {}
    lines = [
        f"# {state.get('roadmap_title', 'Milestone Roadmap')}",
        "",
        "<!-- GENERATED by aidazi roadmap_validator.py from .orchestrator/control/roadmap-state.json. -->",
        "<!-- Do not edit this file directly; change the Control Plane roadmap state/mutations instead. -->",
        "",
        f"- Delivery mode: `{mode}`",
        f"- Active execution source: `{'campaign-plan.json' if mode == 'campaign' else 'charter.yaml'}`",
        f"- Charter: `{refs.get('charter') or 'n/a'}`",
        f"- Campaign plan: `{refs.get('campaign_plan') or 'inactive / not required'}`",
        "",
        "| # | Milestone | Objective | Depends On | Status |",
        "|---|---|---|---|---|",
    ]
    for idx, milestone in enumerate(state.get("milestones") or [], start=1):
        title = milestone.get("title") or milestone.get("id")
        mid = milestone.get("id")
        obj = (milestone.get("objective") or "").replace("\n", " ")
        status = _status_label(milestone.get("status"))
        brief = milestone.get("research_brief")
        if brief:
            status = f"{status}; brief `{brief}`"
        signed = milestone.get("signed_at")
        if signed:
            status = f"{status}; signed {signed}"
        lines.append(
            f"| {idx} | **{mid}** — {title} | {obj} | "
            f"{_deps(milestone.get('depends_on') or [])} | {status} |"
        )
    lines.extend([
        "",
        "## Authority",
        "",
        "- Research briefs are authored by the Research Agent and signed by Customer at gate-1.",
        "- `docs/milestone_objective.md` and sprint objectives are authored by the Deliver Agent.",
        "- In `single_milestone` mode, `charter.yaml` is the active execution contract.",
        "- In `campaign` mode, `campaign-plan.json` is the executable multi-milestone queue.",
        "",
        "---",
        "",
        "End of generated milestone backlog.",
        "",
    ])
    return "\n".join(lines)


def _by_id(items: list[dict]) -> dict[str, dict]:
    return {str(item.get("id")): item for item in items if item.get("id") is not None}


def validate_campaign_alignment(state: dict, campaign_plan: Optional[dict], *,
                                campaign_path: str = "") -> Report:
    report = Report()
    mode = state.get("delivery_mode")
    refs = state.get("source_refs") or {}
    configured = refs.get("campaign_plan")

    if mode == "single_milestone":
        if campaign_plan is not None:
            roadmap_ids = [m.get("id") for m in state.get("milestones") or []]
            campaign_ids = [m.get("id") for m in campaign_plan.get("milestones") or []]
            if roadmap_ids != campaign_ids:
                report.warn(
                    "roadmap_campaign_inactive_drift",
                    "delivery_mode=single_milestone; campaign-plan differs from roadmap but is inactive.",
                    campaign_path,
                )
        return report

    if mode == "campaign":
        if not configured and campaign_plan is None:
            report.error(
                "roadmap_campaign_plan_missing",
                "delivery_mode=campaign requires source_refs.campaign_plan / --campaign-plan.",
            )
            return report
        if campaign_plan is None:
            report.error(
                "roadmap_campaign_plan_unreadable",
                "delivery_mode=campaign requires a readable campaign plan.",
                campaign_path or configured or "",
            )
            return report

        report.merge(_validate_obj(campaign_plan, "campaign-plan.schema.json", path=campaign_path))
        roadmap = state.get("milestones") or []
        campaign = campaign_plan.get("milestones") or []
        roadmap_ids = [m.get("id") for m in roadmap]
        campaign_ids = [m.get("id") for m in campaign]
        if roadmap_ids != campaign_ids:
            report.error(
                "roadmap_campaign_milestone_order_mismatch",
                f"roadmap ids {roadmap_ids} != campaign ids {campaign_ids}",
                campaign_path,
            )
        r_by_id = _by_id(roadmap)
        for c in campaign:
            mid = c.get("id")
            r = r_by_id.get(mid)
            if not r:
                continue
            if list(r.get("depends_on") or []) != list(c.get("depends_on") or []):
                report.error(
                    "roadmap_campaign_dependency_mismatch",
                    f"{mid}: roadmap depends_on {r.get('depends_on') or []} != campaign depends_on {c.get('depends_on') or []}",
                    campaign_path,
                )
            r_seq = list(r.get("subsprint_sequence") or [])
            c_seq = list(c.get("subsprint_sequence") or [])
            if r_seq and c_seq and r_seq != c_seq:
                report.error(
                    "roadmap_campaign_subsprint_mismatch",
                    f"{mid}: roadmap subsprints {r_seq} != campaign subsprints {c_seq}",
                    campaign_path,
                )
    return report


def validate_mutations_file(path: str) -> Report:
    report = Report()
    try:
        with open(path, "r", encoding="utf-8") as fh:
            lines = list(fh)
    except OSError as exc:
        report.error("roadmap_mutation_unreadable", f"could not read mutations JSONL: {exc}", path)
        return report
    for idx, raw in enumerate(lines, start=1):
        if not raw.strip():
            continue
        try:
            obj = json.loads(raw)
        except json.JSONDecodeError as exc:
            report.error("roadmap_mutation_unreadable", f"line {idx}: invalid JSON: {exc}", path)
            continue
        report.merge(_validate_obj(obj, "roadmap-mutation.schema.json", path=f"{path}:{idx}"))
    return report


def validate_state_file(path: str, *, campaign_plan_path: Optional[str] = None) -> Report:
    report = Report()
    try:
        state = _read_json(path)
    except (OSError, json.JSONDecodeError) as exc:
        report.error("roadmap_state_unreadable", f"could not read roadmap state: {exc}", path)
        return report
    report.merge(_validate_obj(state, "roadmap-state.schema.json", path=path))
    if not report.ok:
        return report

    campaign_plan = None
    campaign_path = campaign_plan_path
    if campaign_path is None:
        ref = (state.get("source_refs") or {}).get("campaign_plan")
        if ref:
            campaign_path = ref if os.path.isabs(ref) else os.path.join(os.path.dirname(path), "..", "..", ref)
            campaign_path = os.path.abspath(campaign_path)
    if campaign_path and os.path.isfile(campaign_path):
        try:
            campaign_plan = _read_json(campaign_path)
        except (OSError, json.JSONDecodeError) as exc:
            report.error("roadmap_campaign_plan_unreadable", f"could not read campaign plan: {exc}", campaign_path)
    elif state.get("delivery_mode") == "campaign":
        report.error("roadmap_campaign_plan_unreadable", "campaign plan not found", campaign_path or "")

    report.merge(validate_campaign_alignment(state, campaign_plan, campaign_path=campaign_path or ""))
    return report


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate Control Plane roadmap state and optionally render docs/milestone-backlog.md.",
    )
    parser.add_argument("--state", default=ROADMAP_STATE_REL,
                        help="path to .orchestrator/control/roadmap-state.json")
    parser.add_argument("--mutations", default=None,
                        help="optional roadmap-mutations.jsonl to schema-validate")
    parser.add_argument("--campaign-plan", default=None,
                        help="optional campaign-plan.json for alignment validation")
    parser.add_argument("--render", action="store_true",
                        help="print generated milestone backlog markdown")
    args = parser.parse_args(argv)

    report = validate_state_file(args.state, campaign_plan_path=args.campaign_plan)
    if args.mutations:
        report.merge(validate_mutations_file(args.mutations))
    if args.render and report.ok:
        print(render_backlog(_read_json(args.state)), end="")
    else:
        print(report.render())
    return 0 if report.ok else 1


if __name__ == "__main__":
    sys.exit(main())
